### PR TITLE
render_to_response uses RequestContext

### PR DESCRIPTION
**Pull request by will-moore**
This is https://github.com/will-moore/figure/pull/63 rebased onto master.

This adds RequestContext to render_to_response, making it compatible with changes in openmicroscopy/openmicroscopy#3629.

### CODE REVIEW

**Comment by will-moore** [comment]
@sbesson Merged into master

**Comment by will-moore** [comment]
oops - OK, I didn't do exactly what I planned! This PR merges master into develop, but the fix is already directly in master (with no PR).

**Comment by sbesson** [comment]
Thanks @will-moore deploying now.

**Comment by sbesson** [comment]
@will-moore: okay I thought this was on purpose. This certainly make sense since it will allow the `1.0.1` tag to be part of the `develop` branch.

**Pull request merged**
